apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microshop
type: Opaque
stringData:
  # Secret used for signing JSON Web Tokens. Replace with a strong secret in production.
  JWT_SECRET: supersecret
