apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          # Replace with your Docker Hub repository
          image: shenolosman/microshop-order:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: mongodb://$(MONGO_USER):$(MONGO_PASS)@mongo:27017/order_db
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:5001
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
