apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: microshop
type: Opaque
stringData:
  # Default MongoDB root credentials. Change these for production deployments.
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
